### PR TITLE
CUDA 12

### PR DESCRIPTION
**Pull request by e7d**
- switched to a CUDA 12 based image
- added support for nvidia-smi newer power readings format
- ensures previous power readings format retrocompatibility

### CODE REVIEW

**Comment by e7d** [comment]
Hello @blub3k and @ich777,

Following https://github.com/e7d/docker-prometheus-nvidiasmi/pull/2, and comparing the results on CUDA 11 and CUDA 12, I could see that not only the power node changed names (`power_readings` to `gpu_power_readings`) but also some of it child names.
In the mean time the whole Docker stack was kinda outdated, exposing some bad vulnerabilities in the process.

So I decided to first upgrad the whole stack, including Ubuntu, CUDA and Go, and then do the adjustments, with retrocompatibility in mind.
In the end, if the Docker container runs over a CUDA version < 12 on the host, it will keep the old output. But if the host runs a CUDA version >= 12 it will output both the old format for retrocompability but also a new one respecting the name of the new fields.

Let me know what you think, considering this example ouput from my computer:
```
nvidiasmi_driver_version{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 535.54
nvidiasmi_cuda_version{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 12.2
nvidiasmi_attached_gpus{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1
nvidiasmi_pci_pcie_gen_max{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 4
nvidiasmi_pci_pcie_gen_current{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 4
nvidiasmi_pci_link_width_max_multiplicator{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 16
nvidiasmi_pci_link_width_current_multiplicator{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 16
nvidiasmi_pci_replay_counter{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_pci_replay_rollover_counter{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_pci_tx_util_bytes_per_second{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1e+06
nvidiasmi_pci_rx_util_bytes_per_second{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 3e+06
nvidiasmi_fan_speed_percent{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_performance_state_int{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2
nvidiasmi_fb_memory_usage_total_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.073741824e+10
nvidiasmi_fb_memory_usage_used_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.058013184e+09
nvidiasmi_fb_memory_usage_free_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 9.434038272e+09
nvidiasmi_bar1_memory_usage_total_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.7179869184e+10
nvidiasmi_bar1_memory_usage_used_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.1534336e+07
nvidiasmi_bar1_memory_usage_free_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.7168334848e+10
nvidiasmi_utilization_gpu_percent{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 4
nvidiasmi_utilization_memory_percent{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2
nvidiasmi_utilization_encoder_percent{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_utilization_decoder_percent{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_encoder_session_count{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_encoder_average_fps{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_encoder_average_latency{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_fbc_session_count{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_fbc_average_fps{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_fbc_average_latency{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_gpu_temp_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 52
nvidiasmi_gpu_temp_max_threshold_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 98
nvidiasmi_gpu_temp_slow_threshold_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 95
nvidiasmi_gpu_temp_max_gpu_threshold_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 93
nvidiasmi_memory_temp_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_gpu_temp_max_mem_threshold_celsius{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_power_state_int{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2
nvidiasmi_power_draw_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 111.30999755859375
nvidiasmi_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_default_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_enforced_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_min_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 100
nvidiasmi_max_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 430
nvidiasmi_gpu_power_state_int{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2
nvidiasmi_gpu_power_draw_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 111.30999755859375
nvidiasmi_gpu_current_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_gpu_requested_power_limit{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_gpu_default_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 370
nvidiasmi_gpu_min_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 100
nvidiasmi_gpu_max_power_limit_watts{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 430
nvidiasmi_clock_graphics_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.905e+09
nvidiasmi_clock_graphics_max_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2.13e+09
nvidiasmi_clock_sm_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.905e+09
nvidiasmi_clock_sm_max_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 2.13e+09
nvidiasmi_clock_mem_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 9.251e+09
nvidiasmi_clock_mem_max_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 9.501e+09
nvidiasmi_clock_video_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.665e+09
nvidiasmi_clock_video_max_hertz{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 1.95e+09
nvidiasmi_clock_policy_auto_boost{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_clock_policy_auto_boost_default{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080"} 0
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="10210",process_name="",process_type="G"} 3.97410304e+08
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="10445",process_name="",process_type="C+G"} 2.27540992e+08
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="10507",process_name="",process_type="G"} 6.3963136e+07
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="11661",process_name="",process_type="G"} 2.3068672e+07
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="14129",process_name="",process_type="G"} 9.0177536e+07
nvidiasmi_process_used_memory_bytes{id="00000000:2D:00.0",uuid="GPU-d1e7df6a-33ce-6908-4718-9114ba7cae1f",name="NVIDIA GeForce RTX 3080",process_pid="14449",process_name="",process_type="G"} 2.21249536e+08
```

Please try yourself, using the following docker image: `e7db/prometheus-nvidiasmi:cuda12`

**Comment by ich777** [comment]
@e7d this has nothing to do with the CUDA output, they changed the XML output from `nvidia-smi`

**Comment by e7d** [comment]
> @e7d this has nothing to do with the CUDA output, they changed the XML output from `nvidia-smi`

That makes more sense, yeah. 🤦‍♂️
Nevertheless, my changes should handle both nvidia-smi output formats, don't you think?

**Comment by ich777** [comment]
I'm not too sure, I'll have to try this later today on my test system.

The PR that @blub3k created should be enough since Golang will search for both:
```
		} `xml:"power_readings gpu_power_readings"`
```
and it should parse the xml correctly regardless if the xml entry is `power_readings` or `gpu_power_readings`

I have to try this later today on my test system if everything is working correctly with that change over here.

**Comment by e7d** [comment]
> I'm not too sure, I'll have to try this later today on my test system.
> 
> The PR that @blub3k created should be enough since Golang will search for both:
> 
> ```
> 		} `xml:"power_readings gpu_power_readings"`
> ```
> 
> and it should parse the xml correctly regardless if the xml entry is `power_readings` or `gpu_power_readings`
> 
> I have to try this later today on my test system if everything is working correctly with that change over here.

I get that.
I mean I did not research the go documentation to back up what you say, but I understand the principle.
And still, trying the solution did not work. Maybe I did something wrong, I don't know why at this stage, but I was not able to make that work.
Maybe I'll try again later.

But even if that works, that do not look like a good and viable solution to me, as two child nodes are different anyways between the two versions.
That's why I prefered splitting the two parsings, and ensure backwards compatibility for the newer format coming out of the latest versions for `nvidia-smi`.

**Comment by e7d** [comment]
I had to made to seperate build to make it compatible either with CUDA 11 based systems (as my Debian based personal home server) and CUDA 12 based systems (as my Fedora based laptop and gaming station) but eveything seems to work as expected on all of these machines.

To reflect this changes, I had to make two separate tags:
- [`e7db/prometheus-nvidiasmi:cuda12` or `e7db/prometheus-nvidiasmilatest`](https://github.com/e7d/docker-prometheus-nvidiasmi/tree/cuda12/docker/cuda12/Dockerfile)
- [`e7db/prometheus-nvidiasmi:cuda11`](https://github.com/e7d/docker-prometheus-nvidiasmi/tree/cuda12/docker/cuda11/Dockerfile)

Feel free to test on your side and get back to me.

**Pull request merged**
